apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
