apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingr
spec:
  rules:
  - host: {{ .Values.ingresses.front }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-svc
            port:
              number: 8080
  ingressClassName: nginx
